name: Build Frontend

on:
  pull_request:
    paths:
    - 'frontend/**'
    - 'Makefile'
    - '.github/**'

jobs:
  build:
    name: Frontend Build Steps
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [24]

    steps:
    - name: Check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: run ci
      run: |
        make ci
      working-directory: frontend

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 3
